REM  ***************************************************************************
REM  제목 : [최종프로젝트] 하나1PIECE 조각투자 플랫폼 : PLSQL 공통 모듈 패키지 및 프로시저
REM  작성자 : 박경덕
REM  작성 일자 : 2023-08-10 최초 작성 - [계정계] 공통 모듈 패키지
REM  ***************************************************************************
REM                            [공통 라이브러리 선정 업무]
REM  [계정계]: 계좌 개설, 입금 및 출금, 자행 이체, 거래내역 기록, 예외 로그 기록
REM      - 은행 업무의 예외처리 및 트랜잭션 제어 등 무결성 보장을 위해 해당 계정계 업무를 선정했다.
REM
REM  [시스템계]: 레퍼럴 코드 생성, 예외 로그 기록
REM  ***************************************************************************

--------------------------------------------------------------------------------
-- [계정계] HANA_BANK_MNG PACKAGE HEADER 정의
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE HANA_BANK_MNG AS
    -- 예외 처리 로그 작성 프로시저 [AUTONOMOUS TRANSACTION 제어]
    PROCEDURE WRITE_BANK_LOG(
        A_LOG_CODE IN BANK_EXCEPTION_LOG.LOG_CODE%TYPE,
        A_PROGRAM IN BANK_EXCEPTION_LOG.PROGRAM%TYPE,
        A_MSG IN BANK_EXCEPTION_LOG.MSG%TYPE,
        A_NOTE IN BANK_EXCEPTION_LOG.NOTE%TYPE
    );
    
    -- 은행 거래내역 기록 프로시저
    PROCEDURE WRITE_BANK_TRANSACTION(
        A_ACCOUNT_NUMBER IN BANK_TRANSACTION.ACCOUNT_NUMBER%TYPE,
        A_CLASSIFICATION IN BANK_TRANSACTION.CLASSIFICATION%TYPE,
        A_NAME IN BANK_TRANSACTION.NAME%TYPE,
        A_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        A_BALANCE IN BANK_TRANSACTION.BALANCE%TYPE,
        A_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    );
    
    -- 계좌 개설
    PROCEDURE ACCOUNT_OPENING(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_RESIDENT_NUMBER1 IN ACCOUNT.RESIDENT_NUMBER1%TYPE,
        P_RESIDENT_NUMBER2 IN ACCOUNT.RESIDENT_NUMBER2%TYPE,
        P_NAME IN ACCOUNT.NAME%TYPE
    );
    
    -- 입금
    PROCEDURE DEPOSIT(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    );
    
    -- 출금
    PROCEDURE WITHDRAW(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    );
    
    -- 자행 이체
    PROCEDURE TRANSFER(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    );

END HANA_BANK_MNG;
/



--------------------------------------------------------------------------------
-- [계정계] HANA_BANK_MNG PACKAGE BODY 정의
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY HANA_BANK_MNG AS
    -- 사용자 정의 예외 타입 선언
    EXC_WRONG_PASSWORD EXCEPTION; -- 계좌 비밀번호 틀림 예외 발생
    EXC_INSUFFICIENT_BALANCE EXCEPTION; -- 잔액 부족 예외 발생
    
    -- 유효성 검사용 계좌 비밀번호 저장 변수
    PW VARCHAR2(4);


    -- 계정계 예외 처리 로그 작성 프로시저 [AUTONOMOUS TRANSACTION 제어]
    PROCEDURE WRITE_BANK_LOG(
        A_LOG_CODE IN BANK_EXCEPTION_LOG.LOG_CODE%TYPE,
        A_PROGRAM IN BANK_EXCEPTION_LOG.PROGRAM%TYPE,
        A_MSG IN BANK_EXCEPTION_LOG.MSG%TYPE,
        A_NOTE IN BANK_EXCEPTION_LOG.NOTE%TYPE
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION; -- AUTONOMOUS TRANSACTION
    BEGIN
        -- 발생 EXCEPTION을 LOG 테이블에 기록
        INSERT INTO BANK_EXCEPTION_LOG(LOG_CODE, PROGRAM, MSG, NOTE)
          VALUES(A_LOG_CODE, A_PROGRAM, A_MSG, A_NOTE);
          
        -- AUTONOMOUS TRANSACTION 종료
        COMMIT; 
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END WRITE_BANK_LOG;
    
    
    -- 은행 거래내역 기록 프로시저 정의
    PROCEDURE WRITE_BANK_TRANSACTION(
        A_ACCOUNT_NUMBER IN BANK_TRANSACTION.ACCOUNT_NUMBER%TYPE,
        A_CLASSIFICATION IN BANK_TRANSACTION.CLASSIFICATION%TYPE,
        A_NAME IN BANK_TRANSACTION.NAME%TYPE,
        A_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        A_BALANCE IN BANK_TRANSACTION.BALANCE%TYPE,
        A_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    ) IS
    BEGIN
        -- 은행 거래내역을 기록
        INSERT INTO BANK_TRANSACTION(ACCOUNT_NUMBER, CLASSIFICATION, NAME, AMOUNT, BALANCE, RECIPIENT_ACCOUNT_NUMBER)
          VALUES(A_ACCOUNT_NUMBER, A_CLASSIFICATION, A_NAME, A_AMOUNT, A_BALANCE, A_RECIPIENT_ACCOUNT_NUMBER);
          
        -- OLTP Transaction 종료
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:WBT', 'WRITE_BANK_TRANSACTION', SQLERRM, '거래 내역 기록 실패');
    END WRITE_BANK_TRANSACTION;
    
    
    -- 계좌 개설
    PROCEDURE ACCOUNT_OPENING(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_RESIDENT_NUMBER1 IN ACCOUNT.RESIDENT_NUMBER1%TYPE,
        P_RESIDENT_NUMBER2 IN ACCOUNT.RESIDENT_NUMBER2%TYPE,
        P_NAME IN ACCOUNT.NAME%TYPE
    ) IS
    BEGIN
        -- 계좌 생성
        INSERT INTO ACCOUNT(ACCOUNT_NUMBER, PASSWORD, RESIDENT_NUMBER1, RESIDENT_NUMBER2, NAME)
            VALUES(P_ACCOUNT_NUMBER, P_PASSWORD, P_RESIDENT_NUMBER1, P_RESIDENT_NUMBER2, P_NAME);
        
        -- OLTP Transaction 종료
        COMMIT; 
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:AO', 'ACCOUNT_OPENING', SQLERRM, '계좌 개설 실패');
    END ACCOUNT_OPENING;
    
    
    -- 입금
    PROCEDURE DEPOSIT(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    )IS
        OLD_BALANCE NUMBER;
        NEW_BALANCE NUMBER;
    BEGIN
        SELECT BALANCE INTO OLD_BALANCE FROM ACCOUNT WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER;
        NEW_BALANCE := OLD_BALANCE + P_AMOUNT;
        
        -- 계좌 거래 내역 기록
        WRITE_BANK_TRANSACTION(P_ACCOUNT_NUMBER, 'IN', P_NAME, P_AMOUNT, NEW_BALANCE, P_RECIPIENT_ACCOUNT_NUMBER);
        
        -- 입금 반영
        UPDATE ACCOUNT SET 
            BALANCE = NEW_BALANCE
        WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER;
        
        -- OLTP Transaction 종료
        COMMIT; 
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:DEPOSIT', 'DEPOSIT', SQLERRM, '입금 실패');
    END DEPOSIT;
    
    
    -- 출금
    PROCEDURE WITHDRAW(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    )IS
        OLD_BALANCE NUMBER;
        NEW_BALANCE NUMBER;
    BEGIN
        SELECT PASSWORD, BALANCE INTO PW, OLD_BALANCE FROM ACCOUNT WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER;
        -- 계좌 비밀번호 입력 값 유효성 검사
        IF P_PASSWORD != PW THEN
            RAISE EXC_WRONG_PASSWORD;
        END IF;
        
        IF OLD_BALANCE < P_AMOUNT THEN
            RAISE EXC_INSUFFICIENT_BALANCE;
        END IF;
        
        NEW_BALANCE := OLD_BALANCE - P_AMOUNT;
        
        -- 계좌 거래 내역 기록
        WRITE_BANK_TRANSACTION(P_ACCOUNT_NUMBER, 'OUT', P_NAME, P_AMOUNT, NEW_BALANCE, P_RECIPIENT_ACCOUNT_NUMBER);
        
        -- 출금 반영
        UPDATE ACCOUNT SET 
            BALANCE = NEW_BALANCE
        WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER AND PASSWORD = P_PASSWORD;
        
        -- OLTP Transaction 종료
        COMMIT;

    EXCEPTION
        WHEN EXC_INSUFFICIENT_BALANCE THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:WITHDRAW', 'WITHDRAW', 'EXC_INSUFFICIENT_BALANCE', '출금 실패');

        WHEN EXC_WRONG_PASSWORD THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:WITHDRAW', 'WITHDRAW', 'EXC_WRONG_PASSWORD', '출금 실패');

        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:WITHDRAW', 'WITHDRAW', SQLERRM, '출금 실패');
    END WITHDRAW;

    
    -- 자행 이체
    PROCEDURE TRANSFER(
        P_ACCOUNT_NUMBER IN ACCOUNT.ACCOUNT_NUMBER%TYPE,
        P_PASSWORD IN ACCOUNT.PASSWORD%TYPE,
        P_AMOUNT IN BANK_TRANSACTION.AMOUNT%TYPE,
        P_NAME IN BANK_TRANSACTION.NAME%TYPE,
        P_RECIPIENT_ACCOUNT_NUMBER IN BANK_TRANSACTION.RECIPIENT_ACCOUNT_NUMBER%TYPE
    )IS
        OLD_BALANCE NUMBER;
        NEW_BALANCE NUMBER;
    BEGIN
        SELECT PASSWORD, BALANCE INTO PW, OLD_BALANCE FROM ACCOUNT WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER;
        -- 계좌 비밀번호 입력 값 유효성 검사
        IF P_PASSWORD != PW THEN
            RAISE EXC_WRONG_PASSWORD;
        END IF;
        
        IF OLD_BALANCE < P_AMOUNT THEN
            RAISE EXC_INSUFFICIENT_BALANCE;
        END IF;
        
        NEW_BALANCE := OLD_BALANCE - P_AMOUNT;
        
        -- 출금
        WITHDRAW(P_ACCOUNT_NUMBER, P_PASSWORD, P_AMOUNT, P_NAME, P_RECIPIENT_ACCOUNT_NUMBER);
        
        -- 상대 계좌 입금
        DEPOSIT(P_RECIPIENT_ACCOUNT_NUMBER, P_AMOUNT, P_NAME, P_ACCOUNT_NUMBER);
        
        -- OLTP Transaction 종료
        COMMIT; 

    EXCEPTION
        WHEN EXC_INSUFFICIENT_BALANCE THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:TRANSFER', 'TRANSFER', 'EXC_INSUFFICIENT_BALANCE', '이체 실패');

        WHEN EXC_WRONG_PASSWORD THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:TRANSFER', 'TRANSFER', 'EXC_WRONG_PASSWORD', '이체 실패');

        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_BANK_LOG('ERR:TRANSFER', 'TRANSFER', SQLERRM, '이체 실패');
    END TRANSFER;
END HANA_BANK_MNG;
/

-- [시스템계] 공통 모듈
-- 레퍼럴 코드 생성 : 랜덤 5자리 대문자, 숫자 조합 생성
CREATE OR REPLACE FUNCTION GENERATE_REFERRAL_CODE RETURN VARCHAR2 IS
  v_string VARCHAR2(100) := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  v_output VARCHAR2(5) := '';
BEGIN
  FOR i IN 1..5 LOOP
    v_output := v_output || SUBSTR(v_string, DBMS_RANDOM.VALUE(1, 36), 1);
  END LOOP;

  RETURN v_output;
END;
/

